package main

import (
	"fmt"
	red "github.com/go-redis/redis"
	"math/rand"
	"strconv"
	"sync/atomic"
	"time"
)

const (
	letters     = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
	lockCommand = `if redis.call("GET", KEYS[1]) == ARGV[1] then
    redis.call("SET", KEYS[1], ARGV[1], "PX", ARGV[2])
    return "OK"
else
    return redis.call("SET", KEYS[1], ARGV[1], "NX", "PX", ARGV[2])
end`
	delCommand = `if redis.call("GET", KEYS[1]) == ARGV[1] then
    return redis.call("DEL", KEYS[1])
else
    return 0
end`
	randomLen = 16
	// default timeout to prevent deadlocks
	tolerance       = 500 // milliseconds
	millisPerSecond = 1000
)

// A RedisLock is a redis lock.
type RedisLock struct {
	// redis client
	store red.Cmdable
	// Timeout time
	seconds uint32
	// lock key
	key string
	// Lock the value to prevent the lock from being accessed by others
	id string
}

func init() {
	rand.Seed(time.Now().UnixNano())
}

// NewRedisLock returns a RedisLock.
func NewRedisLock(store red.Cmdable, key string) *RedisLock {
	return &RedisLock{
		store: store,
		key:   key,
		// When getting a lock, the value of the lock is generated by a random string
		id: randomStr(randomLen),
	}
}

// Acquire acquires the lock.
func (rl *RedisLock) Acquire() (bool, error) {
	// Acquire the expiration time
	seconds := atomic.LoadUint32(&rl.seconds)
	// Default lock expiration time is 500ms to prevent deadlocks
	resp, err := rl.store.Eval(lockCommand, []string{rl.key}, []string{rl.id, strconv.Itoa(int(seconds)*millisPerSecond + tolerance)}).Result()
	if err == red.Nil {
		return false, nil
	} else if err != nil {
		fmt.Printf("Error on acquiring lock for %s, %s \n", rl.key, err.Error())
		return false, err
	} else if resp == nil {
		return false, nil
	}
	reply, ok := resp.(string)
	if ok && reply == "OK" {
		return true, nil
	}
	fmt.Printf("Unknown reply when acquiring lock for %s: %v \n", rl.key, resp)
	return false, nil
}

// Release releases the lock.
func (rl *RedisLock) Release() (bool, error) {
	resp, err := rl.store.Eval(delCommand, []string{rl.key}, []string{rl.id}).Result()
	if err != nil {
		return false, err
	}
	reply, ok := resp.(int64)
	if !ok {
		return false, nil
	}
	return reply == 1, nil
}

// SetExpire sets the expire.
// Note that it needs to be called before Acquire()
// otherwise the default is 500ms auto-release
func (rl *RedisLock) SetExpire(seconds int) {
	atomic.StoreUint32(&rl.seconds, uint32(seconds))
}
func randomStr(n int) string {
	b := make([]byte, n)
	for i := range b {
		b[i] = letters[rand.Intn(len(letters))]
	}
	return string(b)
}
